name: RedBank
description: A Bank but Red.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  flip_card: ^0.6.0
  sliding_sheet: ^0.5.0
  cupertino_icons: ^1.0.2
  sql_conn: ^0.0.3
  crypto: ^3.0.2
  shared_preferences: ^2.0.15
  pdf: ^3.8.1
  path_provider: ^2.0.10
  file: ^6.1.2
  permission_handler: ^9.2.0
  file_picker: ^4.6.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Black.ttf
        - asset: assets/fonts/Vazir-Bold.ttf
        - asset: assets/fonts/Vazir-Light.ttf
        - asset: assets/fonts/Vazir-Medium.ttf
        - asset: assets/fonts/Vazir-Regular.ttf
        - asset: assets/fonts/Vazir-Thin.ttf
        - asset: assets/fonts/Vazir-Variable.ttf
